#spring:
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3308/user?serverTimezone=UTC&characterEncoding=UTF-8
#        username: user
#        password: user
#        hikari
#jpa:
#    hibernate:
#        ddl-auto: update
#    show-sql: true
#    properties:
#        hibernate:
#            format_sql: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect